//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.14 at 11:57:54 PM EEST 
//


package Sweets;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ingredientType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ingredientType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="water"/>
 *     &lt;enumeration value="sugar"/>
 *     &lt;enumeration value="vanilla"/>
 *     &lt;enumeration value="treacle"/>
 *     &lt;enumeration value="stabilizer"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ingredientType")
@XmlEnum
public enum IngredientType {

    @XmlEnumValue("water")
    WATER("water"),
    @XmlEnumValue("sugar")
    SUGAR("sugar"),
    @XmlEnumValue("vanilla")
    VANILLA("vanilla"),
    @XmlEnumValue("treacle")
    TREACLE("treacle"),
    @XmlEnumValue("stabilizer")
    STABILIZER("stabilizer");
    private final String value;

    IngredientType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IngredientType fromValue(String v) {
        for (IngredientType c: IngredientType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
